(function(){
  async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
  const DEPTS=['Quality Assurance','Quality Control','Manufacturing','Production','Supply Chain','R&D','Clinical Trial','Regulatory Affairs','Pharmacovigilance','Complaint Handling','Opex','Medical Affairs','IT & Digital Operations'];
  const aliases={'QA':'Quality Assurance','QC':'Quality Control'};
  function canonical(v){return aliases[v]||v}
  async function loadScope(){try{const s=await fetch('/api/session',{credentials:'same-origin',cache:'no-store'});const d=await s.json();const user=d.user;const sel=document.getElementById('devDept');if(!sel||!user)return;if(user.role==='SYSTEM_ADMIN'||user.role==='QA'){sel.innerHTML='<option value="">Select</option>'+DEPTS.map(x=>`<option>${x}</option>`).join('');return}const dept=canonical(user.department||'');sel.innerHTML=`<option value="${dept}">${dept}</option>`;sel.value=dept}catch{}}
  async function load(){const list=document.getElementById('deviationList');if(!list)return;try{const d=await api('/api/deviations');list.innerHTML=(d.deviations||[]).map(x=>`<a class="workflow-link" href="deviation.html?id=${encodeURIComponent(x.id)}"><span class="workflow-number">${x.id}</span><span><b>${String(x.title||'').replace(/[<>&"]/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[m]))}</b><small>${x.dept} · ${x.severity} · ${x.status} · Open record →</small></span></a>`).join('')||'<div class="small-message">No deviations in this scope.</div>'}catch(e){if(list)list.innerHTML=`<div class="small-message">Unable to load deviations: ${e.message}</div>`}}
  document.addEventListener('DOMContentLoaded',async()=>{await loadScope();await load();const form=document.getElementById('deviationForm');form?.addEventListener('submit',async e=>{e.preventDefault();const m=document.getElementById('devCreateMessage');m.textContent='Creating deviation…';m.classList.remove('error');try{const payload={dept:document.getElementById('devDept').value,title:document.getElementById('devTitle').value,severity:document.getElementById('devSeverity').value,ref:document.getElementById('devRef').value,description:document.getElementById('devDescription').value,immediate:document.getElementById('devImmediate')?.checked};const d=await api('/api/deviations',{method:'POST',body:JSON.stringify(payload)});m.textContent=`Created ${d.deviation.id}. Opening record…`;location.href='deviation.html?id='+encodeURIComponent(d.deviation.id)}catch(err){m.textContent=`Unable to create deviation: ${err.message}`;m.classList.add('error')}})})
})();
